apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-template-for-gitlab
  title: Python flask template For GITLAB
  description: Provisions a minimalistic flask application
spec:
  owner: development
  type: service

  parameters:
    - title: Fill in some steps
      required: [component_id, environment]
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        environment:
          title: Environment
          type: string
          enum: [dev, prod]

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{ parameters.component_id }}
          app_env: ${{ parameters.environment }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: nexus.nmscreative.com?owner=platform&repo=${{ parameters.component_id }}
        repoVisibility: public
        defaultBranch: main

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
