apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: Modern Next.js web application template
  tags:
    - nextjs
    - react
    - web
    - frontend
  annotations:
    gitlab.com/project-slug: ${{ values.gitlab_project_slug }}
    backstage.io/techdocs-ref: dir:.
  
  links:
    # ───── App URLs ─────
    - url: https://${{ values.app_name }}.${{ values.base_domain }}
      title: Production
      icon: public

    - url: https://${{ values.app_name }}.stage.${{ values.base_domain }}
      title: Staging
      icon: cloud

    # ───── Health ─────
    - url: https://${{ values.app_name }}.${{ values.base_domain }}/health
      title: Health Check – Prod
      icon: health

    - url: https://${{ values.app_name }}.stage.${{ values.base_domain }}/health
      title: Health Check – Stage
      icon: health

    # ───── Argo CD (READ-ONLY) ─────
    - url: https://argocd.popapps.ai/applications/${{ values.app_name }}-prod
      title: Argo CD – Production
      icon: dashboard

    - url: https://argocd.popapps.ai/applications/${{ values.app_name }}-stage
      title: Argo CD – Staging
      icon: dashboard

    # ───── Tooling ─────
    - url: https://grafana.popapps.ai
      title: Grafana
      icon: dashboard

spec:
  type: service
  lifecycle: development
  owner: ${{ values.owner }}
  system: ${{ values.system }}
