apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: An example of a ${{values.app_name}} application.
  annotations:
    # nexus.nmscreative.com/project-slug: group_17_bot/${{ values.app_name }}
    nexus.nmscreative.com/project-slug: ${{ parameters.ownerPath }}/${{ values.app_name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
